### PR TITLE
⚡️ Optimise the Zero Point Threshold in `wad_exp`

### PR DESCRIPTION
**Pull request by engn33r**
#### ✅ PR Checklist

- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed in an [issue](https://github.com/pcaversaccio/snekmate/issues) or in the [discussions](https://github.com/pcaversaccio/snekmate/discussions) section.
- [x] I didn't do anything of this.

---

This PR is for a very small optimization that is possible by increasing the range of values that will take the short logic path of `wad_exp()` and return zero. I am not sure how the previously chosen value of `-42_139_678_854_452_767_551` was selected, but these tests demonstrate the actual turning point when the result of the current `wad_exp()` implementation transitions from 1 to zero.

```solidity
    function testWadExpZeroPoint() public {
        assertEq(math.wad_exp(-41_446_531_673_892_822_312), 1);
        assertEq(math.wad_exp(-41_446_531_673_892_822_313), 0);
    }
```

---

#### 🐶 Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by pcaversaccio** [comment]
@engn33r great catch! The original number stems from Remco's article: https://xn--2-umb.com/22/exp-ln/index.html

Can you please adjust the tests accordingly:

```diff
-  assertEq(math.wad_exp(-42_139_678_854_452_767_551), 0);
+ assertEq(math.wad_exp(-41_446_531_673_892_822_313), 0);
+ assertEq(math.wad_exp(-41_446_531_673_892_822_312), 1);
```

and also update the `.gas-snapshot` file (run `forge snapshot`). After that I will quickly make a `CHANGELOG` entry and merge.

**Comment by engn33r** [comment]
I made the requested changes.

Thanks for sharing the source, I didn't realize that's where the number originated from. I see solmate and solady are using the same value, I'll verify the same change can happen in their implementations and if so I'll link to this PR.

**Comment by pcaversaccio** [comment]
> I made the requested changes.
> 
> Thanks for sharing the source, I didn't realize that's where the number originated from. I see [solmate](https://github.com/transmissions11/solmate/blob/4b47a19038b798b4a33d9749d25e570443520647/src/utils/SignedWadMath.sol#L110) and [solady](https://github.com/Vectorized/solady/blob/a3471859e8b4d725009f54e55965f5586c42edd5/src/utils/FixedPointMathLib.sol#L156) are using the same value, I'll verify the same change can happen in their implementations and if so I'll link to this PR.

FWIW, I already shared it with @Vectorized!

**Comment by Vectorized** [comment]
@engn33r Beautiful optimization!

**Comment by engn33r** [comment]
[Solmate](https://github.com/transmissions11/solmate/pull/405) PR created and @Vectorized beat me to [a PR](https://github.com/Vectorized/solady/pull/756) for solady :+1:

**Comment by pcaversaccio** [comment]
> [Solmate](https://github.com/transmissions11/solmate/pull/405) PR created and solady PR inbound (2 mins)

Sweet, will merge tomorrow (busy day due to Ledger...)

**Comment by pcaversaccio** [comment]
For anyone who wants to understand how to replicate this using [Titanoboa](https://github.com/vyperlang/titanoboa), here a step-by-step guide:

```console
~$ pip install git+https://github.com/vyperlang/titanoboa
~$ git clone https://github.com/pcaversaccio/snekmate.git
~$ cd snekmate/src/utils/
~$ python
>>> import boa
>>> c = boa.load("Math.vy")
>>> c.wad_exp(-41_446_531_673_892_822_312)
1
>>> c.wad_exp(-41_446_531_673_892_822_313)
0
```

**Review by pcaversaccio — APPROVED** [review]
Thx @engn33r!

**Pull request merged**
