### PR TITLE
♻️ Refactor `VyperDeployer` to Allow the Configuration of the Target EVM Version

### PR DESCRIPTION
**Pull request by zobront**
_Edit by @pcaversaccio:_ We refactor the `VyperDeployer` to allow the configuration of the EVM version. The [`VyperDeployer`](./lib/utils/VyperDeployer.sol) contract now offers two overloaded `deployContract` functions that allow the configuration of the target EVM version.

----

_Original text by @zobront:_ 
If snekmate is installed with `forge install pcaversaccio/snekmate` in a fresh forge repo, tests will fail because the VyperDeployer's call to `create` in the assembly block will not properly deploy the contract.

To fix, user just needs to ensure that `evm_version = 'shanghai'` in their `foundry.toml` file.

This PR simply adds a warning to the README to make them aware of this.

---

#### 🐶 Cute Animal Picture

(https://i.pinimg.com/345x/f0/3a/34/f03a349219e07c262f961a9afefb9a66.jpg)

### CODE REVIEW

**Comment by zobront** [comment]
@pcaversaccio Of course, makes sense that it's due to the Vyper version defaulting to Shanghai.

I like your solution a lot, but wouldn't want to burden everyone who uses `deployContract()` with entering an EVM version. 

I assume you're thinking of adding this as a separate function, so that if they include an EVM version then it'll be included, but otherwise will use the existing function? If that's the case, I think that's a great solution and can update the PR to reflect that change.

**Comment by pcaversaccio** [comment]
> @pcaversaccio Of course, makes sense that it's due to the Vyper version defaulting to Shanghai.
> 
> I like your solution a lot, but wouldn't want to burden everyone who uses `deployContract()` with entering an EVM version.
> 
> I assume you're thinking of adding this as a separate function, so that if they include an EVM version then it'll be included, but otherwise will use the existing function? If that's the case, I think that's a great solution and can update the PR to reflect that change.

I pushed my changes into this PR. I simply use an overloading strategy to provide this convenience. Lmk if you agree with this approach.

**Review by pcaversaccio — DISMISSED** [review]

**Comment by zobront** [comment]
Looks great to me, love the solution 🔥

**Review by pcaversaccio — APPROVED** [review]
Did some final cleanups (removed unnecessary return statements as we use named returns and used `calldata` instead of `memory` for the function arguments). Will merged once the CI passed.

**Pull request merged**
